main: fr.bafbi.qsky.Qsky
name: Qsky
version: 0.1
api-version: 1.17
database: true
author: Bafbi#3144
website: https://github.com/Bafbi
descirption: "Plugin custom créé pour Qlf-Sky (Pour tout contact avec l'equipe de developpement, mp : Bafbi#3144)"


depend: [LuckPerms, CrazyAdvancementsAPI]

commands:
    #DataBase / Local relative
    profil:
        aliases: []
        description: "Affiche le profil public d'un joueur."
        permission: qsky.profil
        permission-message: Cette command n'est pas pour toi!
        usage: "§e§oUsage: /<command> <player>"

    money:
        aliases: [balance, argent]
        description: "Affiche le profil public d'un joueur."
        permission: qsky.money
        permission-message: Cette command n'est pas pour toi!
        usage: "§e§oUsage: /<command>"

    farm:
        aliases: [is, island]
        description: "Affiche le menu du serveur."
        permission: qsky.farm
        permission-message: Cette command n'est pas pour toi!
        usage: "§e§oUsage: /<command>"

    spawn:
        aliases: []
        description: "Teleport au spawn."
        permission: qsky.spawn
        permission-message: Cette command n'est pas pour toi!
        usage: "§e§oUsage: /<command>"

    fly:
        aliases: []
        description: "permet au joueur de voler librement"
        permission: qsky.fly
        permission-message: Cette command n'est pas pour toi!
        usage: "§e§oUsage: /<command>"
    # tpa:
    #     aliases: []
    #     description: "permet de faire une demande te tp"
    #     permission: qsky.tpa
    #     permission-message: Cette command n'est pas pour toi!
    #     usage: "§e§oUsage: /<command> <player>"
    qskyrl:
        aliases: []
        description: "reload les configs"
        permission: qsky.qskyrl
        permission-message: Cette command n'est pas pour toi!
        usage: "§e§oUsage: /<command>"

    qskyadv:
        aliases: []
        description: "debug des advancements"
        permission: qsky.qskyadv
        permission-message: Cette command n'est pas pour toi!
        usage: "§e§oUsage: /<command>"

    bypass:
        aliases: []
        description: "permet de bypass les permissions d'une ile"
        permission: qsky.bypass
        permission-message: Cette command n'est pas pour toi!
        usage: "§e§oUsage: /<command> <island/player>"

permissions:
    qsky.*:
        description: Donne accès à toute les commands de Qsky
        default: op
        children:
            qsky.profil: true
            qsky.admin.money: true
            qsky.farm: true
            qsky.spawn: true
            qsky.fly: true
            qsky.qskyrl: true
            qsky.bypass: true
    qsky.spawn:
        description: Donne l'accès de ce téléporter au spawn
    qsky.money:
        description: Donne l'accès à utiliser l'économie 
        children: 
            qsky.money.pay: true
            qsky.money.bal: true
            qsky.money.baltop: true
    qsky.admin.money:
        description: Donne accès à utiliser l'économie de façon admin
        children:
            qsky.money: true
    qsky.farm:
        description: Donne accès à utilisé les iles
        children:
            qsky.farm.sethome: true
            qsky.farm.home: true
            qsky.farm.invite: true
            qsky.farm.join: true
            qsky.farm.reject: true
            qsky.farm.create: true
            qsky.farm.delete: true
            qsky.farm.cancelInvite: true
            qsky.farm.leave: true
            qsky.farm.tp: true

